# sample_rate = 16000
# classes_num = 128    # Number of notes of piano
# begin_note = 21     # MIDI note of A0, the lowest note of a piano.
# segment_seconds = 10.	# Training segment duration
# hop_seconds = 1.
# frames_per_second = 100
# velocity_scale = 128

# sample_rate = 16000
# classes_num = 88    # Number of notes of piano
# begin_note = 21     # MIDI note of A0, the lowest note of a piano.
# segment_seconds = 10.	# Training segment duration
# hop_seconds = 1.
# frames_per_second = 100
# velocity_scale = 128
sample_rate = 16000
classes_num = 128    # Number of notes of piano
begin_note = 0     # MIDI note of A0, the lowest note of a piano.
segment_seconds = 10.	# Training segment duration
# segment_seconds = 7.	# Training segment duration
# hop_seconds = 1.
hop_seconds = 5.
frames_per_second = 100
# frames_per_second = 500
# frames_per_second = 320
velocity_scale = 128